In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from scipy import stats

In [ ]:
df1=pd.read_csv("adult.csv")
print("info:")
print(df1.info(),"\n")

print("description:")
print(df1.describe(),"\n")

print("unique value count:")
print(df1["income"].value_counts(),"\n")

print("missing vaules greater than zero:")
missing_values=df1.isnull().sum()
print(missing_values[missing_values>0])

info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB
None

description:
                age        fnlwgt  educational-num  capital-gain  \
count  48842.000000  4.884200e+04     48842.000000  48842.000000
mean      38.643585  1.896641e+05        10.078089   1079.067626
std       13.710510  1.056040e+05         2.570973   7452.019058
min       17.000000  1.228500e+04         1.000000      0.000000
25%       28.000000  1.175505e+05         9.000000      0.000000
50%       37.000000  1.781445e+05        10.000000      0.000000
75%       48.000000  2.376420e+05        12.000000      0.000000
max       90.000000  1.490400e+06        16.000000  99999.000000

       capital-loss  hours-per-week
count  48842.000000    48842.000000
mean      87.502314       40.422382
std      403.004552       12.391444
min        0.000000        1.000000
25%        0.000000       40.000000
50%        0.000000       40.000000
75%        0.000000       45.000000
max     4356.000000       99.000000

unique value count:
income
<=50K    37155
>50K     11687
Name: count, dtype: int64

missing vaules greater than zero:
Series([], dtype: int64)

In [ ]:
ordinal_encoder = OrdinalEncoder(categories=[["Male", "Female",]])

df_copy1 = df1
df_copy1["gender"] = ordinal_encoder.fit_transform(df_copy1[["gender"]])
print(df_copy1)

       age     workclass  fnlwgt     education  educational-num  \
0       25       Private  226802          11th                7
1       38       Private   89814       HS-grad                9
2       28     Local-gov  336951    Assoc-acdm               12
3       44       Private  160323  Some-college               10
4       18             ?  103497  Some-college               10
...    ...           ...     ...           ...              ...
48837   27       Private  257302    Assoc-acdm               12
48838   40       Private  154374       HS-grad                9
48839   58       Private  151910       HS-grad                9
48840   22       Private  201490       HS-grad                9
48841   52  Self-emp-inc  287927       HS-grad                9

           marital-status         occupation relationship   race  gender  \
0           Never-married  Machine-op-inspct    Own-child  Black     0.0
1      Married-civ-spouse    Farming-fishing      Husband  White     0.0
2      Married-civ-spouse    Protective-serv      Husband  White     0.0
3      Married-civ-spouse  Machine-op-inspct      Husband  Black     0.0
4           Never-married                  ?    Own-child  White     1.0
...                   ...                ...          ...    ...     ...
48837  Married-civ-spouse       Tech-support         Wife  White     1.0
48838  Married-civ-spouse  Machine-op-inspct      Husband  White     0.0
48839             Widowed       Adm-clerical    Unmarried  White     1.0
48840       Never-married       Adm-clerical    Own-child  White     0.0
48841  Married-civ-spouse    Exec-managerial         Wife  White     1.0

       capital-gain  capital-loss  hours-per-week native-country income
0                 0             0              40  United-States  <=50K
1                 0             0              50  United-States  <=50K
2                 0             0              40  United-States   >50K
3              7688             0              40  United-States   >50K
4                 0             0              30  United-States  <=50K
...             ...           ...             ...            ...    ...
48837             0             0              38  United-States  <=50K
48838             0             0              40  United-States   >50K
48839             0             0              40  United-States  <=50K
48840             0             0              20  United-States  <=50K
48841         15024             0              40  United-States   >50K

[48842 rows x 15 columns]

In [ ]:
normalizer = MinMaxScaler()
df1[['hours-per-week']] = normalizer.fit_transform(df1[['hours-per-week']])
df1.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,-0.995129,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,0.0,0,0,0.397959,United-States,<=50K
1,-0.046942,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,0.0,0,0,0.500000,United-States,<=50K
2,-0.776316,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,0.0,0,0,0.397959,United-States,>50K
3,0.390683,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,0.0,7688,0,0.397959,United-States,>50K
4,-1.505691,?,103497,Some-college,10,Never-married,?,Own-child,White,1.0,0,0,0.295918,United-States,<=50K

In [ ]:
scaler = StandardScaler()
df1[['age']] = scaler.fit_transform(df1[['age']])
df1.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,-0.995129,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,0.0,0,0,0.397959,United-States,<=50K
1,-0.046942,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,0.0,0,0,0.500000,United-States,<=50K
2,-0.776316,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,0.0,0,0,0.397959,United-States,>50K
3,0.390683,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,0.0,7688,0,0.397959,United-States,>50K
4,-1.505691,?,103497,Some-college,10,Never-married,?,Own-child,White,1.0,0,0,0.295918,United-States,<=50K

In [ ]:
df2=pd.read_csv("Dataset_of_Diabetes.csv")
print("info:")
print(df2.info(),"\n")

print("description:")
print(df2.describe(),"\n")

print("unique value count:")
print(df2["Urea"].value_counts(),"\n")

print("missing vaules greater than zero:")
missing_values=df2.isnull().sum()
print(missing_values[missing_values>0])

ordinal_encoder = OrdinalEncoder(categories=[["M", "F","f"]])
# Fit and transform the data
df_copy = df2
df_copy["Gender"] = ordinal_encoder.fit_transform(df_copy[["Gender"]])
print(df_copy)

info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   Gender     1000 non-null   object
 3   AGE        1000 non-null   int64
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB
None

description:
                ID     No_Pation          AGE         Urea           Cr  \
count  1000.000000  1.000000e+03  1000.000000  1000.000000  1000.000000
mean    340.500000  2.705514e+05    53.528000     5.124743    68.943000
std     240.397673  3.380758e+06     8.799241     2.935165    59.984747
min       1.000000  1.230000e+02    20.000000     0.500000     6.000000
25%     125.750000  2.406375e+04    51.000000     3.700000    48.000000
50%     300.500000  3.439550e+04    55.000000     4.600000    60.000000
75%     550.250000  4.538425e+04    59.000000     5.700000    73.000000
max     800.000000  7.543566e+07    79.000000    38.900000   800.000000

             HbA1c         Chol           TG          HDL          LDL  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean      8.281160     4.862820     2.349610     1.204750     2.609790
std       2.534003     1.301738     1.401176     0.660414     1.115102
min       0.900000     0.000000     0.300000     0.200000     0.300000
25%       6.500000     4.000000     1.500000     0.900000     1.800000
50%       8.000000     4.800000     2.000000     1.100000     2.500000
75%      10.200000     5.600000     2.900000     1.300000     3.300000
max      16.000000    10.300000    13.800000     9.900000     9.900000

              VLDL          BMI
count  1000.000000  1000.000000
mean      1.854700    29.578020
std       3.663599     4.962388
min       0.100000    19.000000
25%       0.700000    26.000000
50%       0.900000    30.000000
75%       1.500000    33.000000
max      35.000000    47.750000

unique value count:
Urea
4.300     40
4.000     37
5.000     36
4.800     34
4.100     33
          ..
13.300     1
13.500     1
6.833      1
0.500      1
8.900      1
Name: count, Length: 110, dtype: int64

missing vaules greater than zero:
Series([], dtype: int64)
      ID  No_Pation  Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0    502      17975     1.0   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5
1    735      34221     0.0   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6
2    420      47975     1.0   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5
3    680      87656     1.0   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5
4    504      34223     0.0   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4
..   ...        ...     ...  ...   ...  ..    ...   ...  ...  ...  ...   ...
995  200     454317     0.0   71  11.0  97    7.0   7.5  1.7  1.2  1.8   0.6
996  671     876534     0.0   31   3.0  60   12.3   4.1  2.2  0.7  2.4  15.4
997  669      87654     0.0   30   7.1  81    6.7   4.1  1.1  1.2  2.4   8.1
998   99      24004     0.0   38   5.8  59    6.7   5.3  2.0  1.6  2.9  14.0
999  248      24054     0.0   54   5.0  67    6.9   3.8  1.7  1.1  3.0   0.7

      BMI CLASS
0    24.0     N
1    23.0     N
2    24.0     N
3    24.0     N
4    21.0     N
..    ...   ...
995  30.0     Y
996  37.2    Y
997  27.4    Y
998  40.5    Y
999  33.0    Y

[1000 rows x 14 columns]

In [ ]:
normalizer = MinMaxScaler()
df2[['Cr']] = normalizer.fit_transform(df2[['Cr']])
df2.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS,hours-per-week
0,502,17975,1.0,-0.401144,4.7,0.050378,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N,0.050378
1,735,34221,0.0,-3.130017,4.5,0.070529,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N,0.070529
2,420,47975,1.0,-0.401144,4.7,0.050378,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N,0.050378
3,680,87656,1.0,-0.401144,4.7,0.050378,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N,0.050378
4,504,34223,0.0,-2.334096,7.1,0.050378,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N,0.050378

In [ ]:
scaler = StandardScaler()
df2[['AGE']] = scaler.fit_transform(df2[['AGE']])
df2.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS,hours-per-week
0,502,17975,1.0,-0.401144,4.7,0.050378,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N,0.050378
1,735,34221,0.0,-3.130017,4.5,0.070529,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N,0.070529
2,420,47975,1.0,-0.401144,4.7,0.050378,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N,0.050378
3,680,87656,1.0,-0.401144,4.7,0.050378,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N,0.050378
4,504,34223,0.0,-2.334096,7.1,0.050378,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N,0.050378